create table if not exists public.feedback_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  provider text,
  subject text,
  score numeric,
  severity text,
  verdict text,
  feedback_type text,
  message text not null,
  email text,
  user_agent text,
  page_url text
);
